cflags = -lm -g
BIN = getdays_xia
BIN1 = ymkstack_xia
SRC = getdays_xia.c
SRC1 = ymkstack_xia.c

CC = gcc
${BIN} ::
	${CC} $(SRC) -o $(BIN) $(cflags)
	${CC} $(SRC1) -o $(BIN1) $(cflags)
clean ::
	rm -f $(BIN) $(BIN1)

